sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t 315426346/client:latest ./client
  - docker run -e CI=true 315426346/client npm run test

script:
  # 1) build add images
  # 2) login to docker
  # 3) push to docker hub
  - docker build -t 315426346/client:latest ./client
  - docker build -t 315426346/worker:latest ./worker
  - docker build -t 315426346/server:latest ./server

  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_ID --password-stdin

  - docker push 315426346/client:latest 
  - docker push 315426346/worker:latest
  - docker push 315426346/server:latest
