sudo: required
services:
  - docker

before_install:
  docker build -t 315426346/client-test:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 315426346/client-test npm run test

after_success:
  # build
  - docker build -t 315426346/nginx:latest ./nginx
  - docker build -t 315426346/client:latest ./client
  - docker build -t 315426346/server:latest ./server
  - docker build -t 315426346/worker:latest ./worker
  #  login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # push
  - docker push 315426346/nginx
  - docker push 315426346/client
  - docker push 315426346/server
  - docker push 315426346/worker
