version: "3"
services:
  client:
    volumes:
      - ./client:/usr/app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
  api:
    volumes:
      - ./server:/usr/app
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    volumes:
      - ./worker:/usr/app
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: redis:latest
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - client
      - worker
