# Only if this file attached to a pod, only then k8s most find this resources and attach them to the pod

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # only one node can access this volume
  resources:
    requests:
      storage: 2Gi